" syntax highlight                                                                                                        
syntax on                                                                                                                 
                                                                                                                          
" show line number                                                                                                        
set number                                                                                                                
                                                                                                                          
" no wrap                                                                                                                 
set nowrap                                                                                                                
                                                                                                                          
" no underline for cursorline                                                                                             
hi cursorline cterm=none                                                                                                  
                                                                                                                          
" quick normal model                                                                                                      
imap jj <Esc>                                                                                                             
                                                                                                                          
" scroll one line up/down                                                                                                 
nmap <C-n> <C-e>                                                                                                          
nmap <C-p> <C-y>                                                                                                          
                                                                                                                          
" switch windows                                                                                                          
nmap <C-o><C-o> <C-w><C-w>                                                                                                
                                                                                                                          
" beginning / end of line                                                                                                 
inoremap <C-e> <Esc>A                                                                                                     
inoremap <C-a> <Esc>I                                                                                                     
                                                                                                                          
" filetype plugin                                                                                                         
filetype plugin indent on                                                                                                 
                                                                                                                          
" show existing tab with 4 spaces                                                                                         
set tabstop=4                                                                                                             
                                                                                                                          
" when indenting with '>' use 4 spaces                                                                                    
set shiftwidth=4                                                                                                          
                                                                                                                          
" on pressing tab, insert 4 spaces                                                                                        
set expandtab                                                                                                             
                                                                                                                          
" show status line                                                                                                        
set laststatus=2                                                                                                          
set statusline=[%n]\ %<%f%h%m                                                                                             
                                  
