/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Calc.xs. Do not edit this file, edit Calc.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Calc.xs"


/*****************************************************************************/
/*                                                                           */
/*    Copyright (c) 1995 - 2004 by Steffen Beyer.                            */
/*    All rights reserved.                                                   */
/*                                                                           */
/*    This package is free software; you can redistribute it                 */
/*    and/or modify it under the same terms as Perl itself.                  */
/*                                                                           */
/*****************************************************************************/


#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"


#include "patchlevel.h"
#if ((PATCHLEVEL < 4) || ((PATCHLEVEL == 4) && (SUBVERSION < 5)))
/* PL_na was introduced in perl5.004_05 */
#ifndef PL_na
    #define PL_na na
#endif
#endif
#if (PATCHLEVEL < 4)
/* GIMME_V was introduced in perl5.004 */
#ifndef GIMME_V
    #define GIMME_V GIMME
#endif
#endif


#include "DateCalc.h"


const char *_DateCalc_DATE_ERROR       = "not a valid date";
const char *_DateCalc_TIME_ERROR       = "not a valid time";
const char *_DateCalc_YEAR_ERROR       = "year out of range";
const char *_DateCalc_MONTH_ERROR      = "month out of range";
const char *_DateCalc_WEEK_ERROR       = "week out of range";
const char *_DateCalc_DAYOFWEEK_ERROR  = "day of week out of range";
const char *_DateCalc_DATE_RANGE_ERROR = "date out of range";
const char *_DateCalc_TIME_RANGE_ERROR = "time out of range";
const char *_DateCalc_FACTOR_ERROR     = "factor out of range";
const char *_DateCalc_LANGUAGE_ERROR   = "language not available";
const char *_DateCalc_SYSTEM_ERROR     = "not available on this system";
const char *_DateCalc_MEMORY_ERROR     = "unable to allocate memory";
const char *_DateCalc_STRING_ERROR     = "argument is not a string";


#define DATECALC_STRING(ref,var,len) \
    ( ref && !(SvROK(ref)) && SvPOK(ref) && \
    (var = (charptr)SvPV(ref,PL_na)) && \
    ((len = (N_int)SvCUR(ref)) | 1) )


#define DATECALC_ERROR(message) \
    croak("Date::Calc::%s(): %s", GvNAME(CvGV(cv)), message)


#define DATECALC_DATE_ERROR \
    DATECALC_ERROR( _DateCalc_DATE_ERROR )

#define DATECALC_TIME_ERROR \
    DATECALC_ERROR( _DateCalc_TIME_ERROR )

#define DATECALC_YEAR_ERROR \
    DATECALC_ERROR( _DateCalc_YEAR_ERROR )

#define DATECALC_MONTH_ERROR \
    DATECALC_ERROR( _DateCalc_MONTH_ERROR )

#define DATECALC_WEEK_ERROR \
    DATECALC_ERROR( _DateCalc_WEEK_ERROR )

#define DATECALC_DAYOFWEEK_ERROR \
    DATECALC_ERROR( _DateCalc_DAYOFWEEK_ERROR )

#define DATECALC_DATE_RANGE_ERROR \
    DATECALC_ERROR( _DateCalc_DATE_RANGE_ERROR )

#define DATECALC_TIME_RANGE_ERROR \
    DATECALC_ERROR( _DateCalc_TIME_RANGE_ERROR )

#define DATECALC_FACTOR_ERROR \
    DATECALC_ERROR( _DateCalc_FACTOR_ERROR )

#define DATECALC_LANGUAGE_ERROR \
    DATECALC_ERROR( _DateCalc_LANGUAGE_ERROR )

#define DATECALC_SYSTEM_ERROR \
    DATECALC_ERROR( _DateCalc_SYSTEM_ERROR )

#define DATECALC_MEMORY_ERROR \
    DATECALC_ERROR( _DateCalc_MEMORY_ERROR )

#define DATECALC_STRING_ERROR \
    DATECALC_ERROR( _DateCalc_STRING_ERROR )


#line 112 "Calc.c"
XS(XS_Date__Calc_Days_in_Year); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Days_in_Year)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Date::Calc::Days_in_Year(year, month)");
    SP -= items;
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
#line 113 "Calc.xs"
{
    if (year > 0)
    {
        if ((month >= 1) and (month <= 12))
        {
            EXTEND(sp,1);
            PUSHs(sv_2mortal(newSViv((IV)DateCalc_Days_in_Year_[DateCalc_leap_year(year)][month+1])));
        }
        else DATECALC_MONTH_ERROR;
    }
    else DATECALC_YEAR_ERROR;
}
#line 136 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Days_in_Month); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Days_in_Month)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Date::Calc::Days_in_Month(year, month)");
    SP -= items;
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
#line 132 "Calc.xs"
{
    if (year > 0)
    {
        if ((month >= 1) and (month <= 12))
        {
            EXTEND(sp,1);
            PUSHs(sv_2mortal(newSViv((IV)DateCalc_Days_in_Month_[DateCalc_leap_year(year)][month])));
        }
        else DATECALC_MONTH_ERROR;
    }
    else DATECALC_YEAR_ERROR;
}
#line 165 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Weeks_in_Year); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Weeks_in_Year)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::Weeks_in_Year(year)");
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	RETVAL;
	dXSTARG;
#line 150 "Calc.xs"
{
    if (year > 0)
    {
        RETVAL = DateCalc_Weeks_in_Year(year);
    }
    else DATECALC_YEAR_ERROR;
}
#line 189 "Calc.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_leap_year); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_leap_year)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::leap_year(year)");
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	boolean	RETVAL;
	dXSTARG;
#line 165 "Calc.xs"
{
    if (year > 0)
    {
        RETVAL = DateCalc_leap_year(year);
    }
    else DATECALC_YEAR_ERROR;
}
#line 213 "Calc.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_check_date); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_check_date)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Calc::check_date(year, month, day)");
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
	Z_int	day = (Z_int)SvIV(ST(2));
	boolean	RETVAL;
	dXSTARG;

	RETVAL = DateCalc_check_date(year, month, day);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_check_time); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_check_time)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Calc::check_time(hour, min, sec)");
    {
	Z_int	hour = (Z_int)SvIV(ST(0));
	Z_int	min = (Z_int)SvIV(ST(1));
	Z_int	sec = (Z_int)SvIV(ST(2));
	boolean	RETVAL;
	dXSTARG;

	RETVAL = DateCalc_check_time(hour, min, sec);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_check_business_date); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_check_business_date)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Calc::check_business_date(year, week, dow)");
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	week = (Z_int)SvIV(ST(1));
	Z_int	dow = (Z_int)SvIV(ST(2));
	boolean	RETVAL;
	dXSTARG;

	RETVAL = DateCalc_check_business_date(year, week, dow);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_Day_of_Year); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Day_of_Year)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Calc::Day_of_Year(year, month, day)");
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
	Z_int	day = (Z_int)SvIV(ST(2));
	Z_int	RETVAL;
	dXSTARG;
#line 203 "Calc.xs"
{
    RETVAL = DateCalc_Day_of_Year(year,month,day);
    if (RETVAL == 0) DATECALC_DATE_ERROR;
}
#line 293 "Calc.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_Date_to_Days); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Date_to_Days)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Calc::Date_to_Days(year, month, day)");
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
	Z_int	day = (Z_int)SvIV(ST(2));
	Z_long	RETVAL;
	dXSTARG;
#line 217 "Calc.xs"
{
    RETVAL = DateCalc_Date_to_Days(year,month,day);
    if (RETVAL == 0) DATECALC_DATE_ERROR;
}
#line 316 "Calc.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_Day_of_Week); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Day_of_Week)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Calc::Day_of_Week(year, month, day)");
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
	Z_int	day = (Z_int)SvIV(ST(2));
	Z_int	RETVAL;
	dXSTARG;
#line 231 "Calc.xs"
{
    RETVAL = DateCalc_Day_of_Week(year,month,day);
    if (RETVAL == 0) DATECALC_DATE_ERROR;
}
#line 339 "Calc.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_Week_Number); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Week_Number)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Calc::Week_Number(year, month, day)");
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
	Z_int	day = (Z_int)SvIV(ST(2));
	Z_int	RETVAL;
	dXSTARG;
#line 245 "Calc.xs"
{
    if (DateCalc_check_date(year,month,day))
    {
        RETVAL = DateCalc_Week_Number(year,month,day);
    }
    else DATECALC_DATE_ERROR;
}
#line 365 "Calc.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_Week_of_Year); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Week_of_Year)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Calc::Week_of_Year(year, month, day)");
    SP -= items;
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
	Z_int	day = (Z_int)SvIV(ST(2));
#line 262 "Calc.xs"
{
    Z_int week;

    if (DateCalc_week_of_year(&week,&year,month,day))
    {
        if (GIMME_V == G_ARRAY)
        {
            EXTEND(sp,2);
            PUSHs(sv_2mortal(newSViv((IV)week)));
            PUSHs(sv_2mortal(newSViv((IV)year)));
        }
        else
        {
            EXTEND(sp,1);
            PUSHs(sv_2mortal(newSViv((IV)week)));
        }
    }
    else DATECALC_DATE_ERROR;
}
#line 402 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Monday_of_Week); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Monday_of_Week)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Date::Calc::Monday_of_Week(week, year)");
    SP -= items;
    {
	Z_int	week = (Z_int)SvIV(ST(0));
	Z_int	year = (Z_int)SvIV(ST(1));
#line 288 "Calc.xs"
{
    Z_int month;
    Z_int day;

    if (year > 0)
    {
        if ((week > 0) and (week <= DateCalc_Weeks_in_Year(year)))
        {
            if (DateCalc_monday_of_week(week,&year,&month,&day))
            {
                EXTEND(sp,3);
                PUSHs(sv_2mortal(newSViv((IV)year)));
                PUSHs(sv_2mortal(newSViv((IV)month)));
                PUSHs(sv_2mortal(newSViv((IV)day)));
            }
            else DATECALC_DATE_ERROR;
        }
        else DATECALC_WEEK_ERROR;
    }
    else DATECALC_YEAR_ERROR;
}
#line 440 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Nth_Weekday_of_Month_Year); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Nth_Weekday_of_Month_Year)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: Date::Calc::Nth_Weekday_of_Month_Year(year, month, dow, n)");
    SP -= items;
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
	Z_int	dow = (Z_int)SvIV(ST(2));
	Z_int	n = (Z_int)SvIV(ST(3));
#line 318 "Calc.xs"
{
    Z_int day;

    if (year > 0)
    {
        if ((month >= 1) and (month <= 12))
        {
            if ((dow >= 1) and (dow <= 7))
            {
                if ((n >= 1) and (n <= 5))
                {
                    if (DateCalc_nth_weekday_of_month_year(&year,&month,&day,dow,n))
                    {
                        EXTEND(sp,3);
                        PUSHs(sv_2mortal(newSViv((IV)year)));
                        PUSHs(sv_2mortal(newSViv((IV)month)));
                        PUSHs(sv_2mortal(newSViv((IV)day)));
                    }
                    /* else return empty list */
                }
                else DATECALC_FACTOR_ERROR;
            }
            else DATECALC_DAYOFWEEK_ERROR;
        }
        else DATECALC_MONTH_ERROR;
    }
    else DATECALC_YEAR_ERROR;
}
#line 487 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Standard_to_Business); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Standard_to_Business)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Calc::Standard_to_Business(year, month, day)");
    SP -= items;
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
	Z_int	day = (Z_int)SvIV(ST(2));
#line 354 "Calc.xs"
{
    Z_int week;
    Z_int dow;

    if (DateCalc_standard_to_business(&year,&week,&dow,month,day))
    {
        EXTEND(sp,3);
        PUSHs(sv_2mortal(newSViv((IV)year)));
        PUSHs(sv_2mortal(newSViv((IV)week)));
        PUSHs(sv_2mortal(newSViv((IV)dow)));
    }
    else DATECALC_DATE_ERROR;
}
#line 518 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Business_to_Standard); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Business_to_Standard)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Calc::Business_to_Standard(year, week, dow)");
    SP -= items;
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	week = (Z_int)SvIV(ST(1));
	Z_int	dow = (Z_int)SvIV(ST(2));
#line 375 "Calc.xs"
{
    Z_int month;
    Z_int day;

    if (DateCalc_business_to_standard(&year,&month,&day,week,dow))
    {
        EXTEND(sp,3);
        PUSHs(sv_2mortal(newSViv((IV)year)));
        PUSHs(sv_2mortal(newSViv((IV)month)));
        PUSHs(sv_2mortal(newSViv((IV)day)));
    }
    else DATECALC_DATE_ERROR;
}
#line 549 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Delta_Days); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Delta_Days)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: Date::Calc::Delta_Days(year1, month1, day1, year2, month2, day2)");
    {
	Z_int	year1 = (Z_int)SvIV(ST(0));
	Z_int	month1 = (Z_int)SvIV(ST(1));
	Z_int	day1 = (Z_int)SvIV(ST(2));
	Z_int	year2 = (Z_int)SvIV(ST(3));
	Z_int	month2 = (Z_int)SvIV(ST(4));
	Z_int	day2 = (Z_int)SvIV(ST(5));
	Z_long	RETVAL;
	dXSTARG;
#line 399 "Calc.xs"
{
    if (DateCalc_check_date(year1,month1,day1) and
        DateCalc_check_date(year2,month2,day2))
    {
        RETVAL = DateCalc_Delta_Days(year1,month1,day1, year2,month2,day2);
    }
    else DATECALC_DATE_ERROR;
}
#line 579 "Calc.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_Delta_DHMS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Delta_DHMS)
{
    dXSARGS;
    if (items != 12)
	Perl_croak(aTHX_ "Usage: Date::Calc::Delta_DHMS(year1, month1, day1, hour1, min1, sec1, year2, month2, day2, hour2, min2, sec2)");
    SP -= items;
    {
	Z_int	year1 = (Z_int)SvIV(ST(0));
	Z_int	month1 = (Z_int)SvIV(ST(1));
	Z_int	day1 = (Z_int)SvIV(ST(2));
	Z_int	hour1 = (Z_int)SvIV(ST(3));
	Z_int	min1 = (Z_int)SvIV(ST(4));
	Z_int	sec1 = (Z_int)SvIV(ST(5));
	Z_int	year2 = (Z_int)SvIV(ST(6));
	Z_int	month2 = (Z_int)SvIV(ST(7));
	Z_int	day2 = (Z_int)SvIV(ST(8));
	Z_int	hour2 = (Z_int)SvIV(ST(9));
	Z_int	min2 = (Z_int)SvIV(ST(10));
	Z_int	sec2 = (Z_int)SvIV(ST(11));
#line 426 "Calc.xs"
{
    Z_long Dd;
    Z_int  Dh;
    Z_int  Dm;
    Z_int  Ds;

    if (DateCalc_check_date(year1,month1,day1) and
        DateCalc_check_date(year2,month2,day2))
    {
        if (DateCalc_check_time(hour1,min1,sec1) and
            DateCalc_check_time(hour2,min2,sec2))
        {
            if (DateCalc_delta_dhms(&Dd,&Dh,&Dm,&Ds,
                                    year1,month1,day1, hour1,min1,sec1,
                                    year2,month2,day2, hour2,min2,sec2))
            {
                EXTEND(sp,4);
                PUSHs(sv_2mortal(newSViv((IV)Dd)));
                PUSHs(sv_2mortal(newSViv((IV)Dh)));
                PUSHs(sv_2mortal(newSViv((IV)Dm)));
                PUSHs(sv_2mortal(newSViv((IV)Ds)));
            }
            else DATECALC_DATE_ERROR;
        }
        else DATECALC_TIME_ERROR;
    }
    else DATECALC_DATE_ERROR;
}
#line 634 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Delta_YMD); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Delta_YMD)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: Date::Calc::Delta_YMD(year1, month1, day1, year2, month2, day2)");
    SP -= items;
    {
	Z_int	year1 = (Z_int)SvIV(ST(0));
	Z_int	month1 = (Z_int)SvIV(ST(1));
	Z_int	day1 = (Z_int)SvIV(ST(2));
	Z_int	year2 = (Z_int)SvIV(ST(3));
	Z_int	month2 = (Z_int)SvIV(ST(4));
	Z_int	day2 = (Z_int)SvIV(ST(5));
#line 465 "Calc.xs"
{
    if (DateCalc_delta_ymd(&year1,&month1,&day1, year2,month2,day2))
    {
        EXTEND(sp,3);
        PUSHs(sv_2mortal(newSViv((IV)year1)));
        PUSHs(sv_2mortal(newSViv((IV)month1)));
        PUSHs(sv_2mortal(newSViv((IV)day1)));
    }
    else DATECALC_DATE_ERROR;
}
#line 665 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Delta_YMDHMS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Delta_YMDHMS)
{
    dXSARGS;
    if (items != 12)
	Perl_croak(aTHX_ "Usage: Date::Calc::Delta_YMDHMS(year1, month1, day1, hour1, min1, sec1, year2, month2, day2, hour2, min2, sec2)");
    SP -= items;
    {
	Z_int	year1 = (Z_int)SvIV(ST(0));
	Z_int	month1 = (Z_int)SvIV(ST(1));
	Z_int	day1 = (Z_int)SvIV(ST(2));
	Z_int	hour1 = (Z_int)SvIV(ST(3));
	Z_int	min1 = (Z_int)SvIV(ST(4));
	Z_int	sec1 = (Z_int)SvIV(ST(5));
	Z_int	year2 = (Z_int)SvIV(ST(6));
	Z_int	month2 = (Z_int)SvIV(ST(7));
	Z_int	day2 = (Z_int)SvIV(ST(8));
	Z_int	hour2 = (Z_int)SvIV(ST(9));
	Z_int	min2 = (Z_int)SvIV(ST(10));
	Z_int	sec2 = (Z_int)SvIV(ST(11));
#line 492 "Calc.xs"
{
    Z_int  D_y;
    Z_int  D_m;
    Z_int  D_d;
    Z_int  Dh;
    Z_int  Dm;
    Z_int  Ds;

    if (DateCalc_check_date(year1,month1,day1) and
        DateCalc_check_date(year2,month2,day2))
    {
        if (DateCalc_check_time(hour1,min1,sec1) and
            DateCalc_check_time(hour2,min2,sec2))
        {
            if (DateCalc_delta_ymdhms(&D_y,&D_m,&D_d,    &Dh,&Dm,&Ds,
                                      year1,month1,day1, hour1,min1,sec1,
                                      year2,month2,day2, hour2,min2,sec2))
            {
                EXTEND(sp,6);
                PUSHs(sv_2mortal(newSViv((IV)D_y)));
                PUSHs(sv_2mortal(newSViv((IV)D_m)));
                PUSHs(sv_2mortal(newSViv((IV)D_d)));
                PUSHs(sv_2mortal(newSViv((IV)Dh)));
                PUSHs(sv_2mortal(newSViv((IV)Dm)));
                PUSHs(sv_2mortal(newSViv((IV)Ds)));
            }
            else DATECALC_DATE_ERROR;
        }
        else DATECALC_TIME_ERROR;
    }
    else DATECALC_DATE_ERROR;
}
#line 724 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Normalize_DHMS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Normalize_DHMS)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: Date::Calc::Normalize_DHMS(Dd, Dh, Dm, Ds)");
    SP -= items;
    {
	Z_long	Dd = (Z_long)SvIV(ST(0));
	Z_long	Dh = (Z_long)SvIV(ST(1));
	Z_long	Dm = (Z_long)SvIV(ST(2));
	Z_long	Ds = (Z_long)SvIV(ST(3));
#line 533 "Calc.xs"
{
    DateCalc_Normalize_DHMS(&Dd,&Dh,&Dm,&Ds);
    EXTEND(sp,4);
    PUSHs(sv_2mortal(newSViv((IV)Dd)));
    PUSHs(sv_2mortal(newSViv((IV)Dh)));
    PUSHs(sv_2mortal(newSViv((IV)Dm)));
    PUSHs(sv_2mortal(newSViv((IV)Ds)));
}
#line 751 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Add_Delta_Days); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Add_Delta_Days)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: Date::Calc::Add_Delta_Days(year, month, day, Dd)");
    SP -= items;
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
	Z_int	day = (Z_int)SvIV(ST(2));
	Z_long	Dd = (Z_long)SvIV(ST(3));
#line 550 "Calc.xs"
{
    if (DateCalc_add_delta_days(&year,&month,&day, Dd))
    {
        EXTEND(sp,3);
        PUSHs(sv_2mortal(newSViv((IV)year)));
        PUSHs(sv_2mortal(newSViv((IV)month)));
        PUSHs(sv_2mortal(newSViv((IV)day)));
    }
    else DATECALC_DATE_ERROR;
}
#line 780 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Add_Delta_DHMS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Add_Delta_DHMS)
{
    dXSARGS;
    if (items != 10)
	Perl_croak(aTHX_ "Usage: Date::Calc::Add_Delta_DHMS(year, month, day, hour, min, sec, Dd, Dh, Dm, Ds)");
    SP -= items;
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
	Z_int	day = (Z_int)SvIV(ST(2));
	Z_int	hour = (Z_int)SvIV(ST(3));
	Z_int	min = (Z_int)SvIV(ST(4));
	Z_int	sec = (Z_int)SvIV(ST(5));
	Z_long	Dd = (Z_long)SvIV(ST(6));
	Z_long	Dh = (Z_long)SvIV(ST(7));
	Z_long	Dm = (Z_long)SvIV(ST(8));
	Z_long	Ds = (Z_long)SvIV(ST(9));
#line 575 "Calc.xs"
{
    if (DateCalc_check_date(year,month,day))
    {
        if (DateCalc_check_time(hour,min,sec))
        {
            if (DateCalc_add_delta_dhms(&year,&month,&day,
                                        &hour,&min,&sec,
                                        Dd,Dh,Dm,Ds))
            {
                EXTEND(sp,6);
                PUSHs(sv_2mortal(newSViv((IV)year)));
                PUSHs(sv_2mortal(newSViv((IV)month)));
                PUSHs(sv_2mortal(newSViv((IV)day)));
                PUSHs(sv_2mortal(newSViv((IV)hour)));
                PUSHs(sv_2mortal(newSViv((IV)min)));
                PUSHs(sv_2mortal(newSViv((IV)sec)));
            }
            else DATECALC_DATE_ERROR;
        }
        else DATECALC_TIME_ERROR;
    }
    else DATECALC_DATE_ERROR;
}
#line 828 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Add_Delta_YM); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Add_Delta_YM)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: Date::Calc::Add_Delta_YM(year, month, day, Dy, Dm)");
    SP -= items;
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
	Z_int	day = (Z_int)SvIV(ST(2));
	Z_long	Dy = (Z_long)SvIV(ST(3));
	Z_long	Dm = (Z_long)SvIV(ST(4));
#line 608 "Calc.xs"
{
    if (DateCalc_add_delta_ym(&year,&month,&day, Dy,Dm))
    {
        EXTEND(sp,3);
        PUSHs(sv_2mortal(newSViv((IV)year)));
        PUSHs(sv_2mortal(newSViv((IV)month)));
        PUSHs(sv_2mortal(newSViv((IV)day)));
    }
    else DATECALC_DATE_ERROR;
}
#line 858 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Add_Delta_YMD); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Add_Delta_YMD)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: Date::Calc::Add_Delta_YMD(year, month, day, Dy, Dm, Dd)");
    SP -= items;
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
	Z_int	day = (Z_int)SvIV(ST(2));
	Z_long	Dy = (Z_long)SvIV(ST(3));
	Z_long	Dm = (Z_long)SvIV(ST(4));
	Z_long	Dd = (Z_long)SvIV(ST(5));
#line 629 "Calc.xs"
{
    if (DateCalc_add_delta_ymd(&year,&month,&day, Dy,Dm,Dd))
    {
        EXTEND(sp,3);
        PUSHs(sv_2mortal(newSViv((IV)year)));
        PUSHs(sv_2mortal(newSViv((IV)month)));
        PUSHs(sv_2mortal(newSViv((IV)day)));
    }
    else DATECALC_DATE_ERROR;
}
#line 889 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Add_Delta_YMDHMS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Add_Delta_YMDHMS)
{
    dXSARGS;
    if (items != 12)
	Perl_croak(aTHX_ "Usage: Date::Calc::Add_Delta_YMDHMS(year, month, day, hour, min, sec, D_y, D_m, D_d, Dh, Dm, Ds)");
    SP -= items;
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
	Z_int	day = (Z_int)SvIV(ST(2));
	Z_int	hour = (Z_int)SvIV(ST(3));
	Z_int	min = (Z_int)SvIV(ST(4));
	Z_int	sec = (Z_int)SvIV(ST(5));
	Z_long	D_y = (Z_long)SvIV(ST(6));
	Z_long	D_m = (Z_long)SvIV(ST(7));
	Z_long	D_d = (Z_long)SvIV(ST(8));
	Z_long	Dh = (Z_long)SvIV(ST(9));
	Z_long	Dm = (Z_long)SvIV(ST(10));
	Z_long	Ds = (Z_long)SvIV(ST(11));
#line 656 "Calc.xs"
{
    if (DateCalc_check_date(year,month,day))
    {
        if (DateCalc_check_time(hour,min,sec))
        {
            if (DateCalc_add_delta_ymdhms(&year,&month,&day,
                                          &hour,&min,&sec,
                                          D_y,D_m,D_d,
                                          Dh,Dm,Ds))
            {
                EXTEND(sp,6);
                PUSHs(sv_2mortal(newSViv((IV)year)));
                PUSHs(sv_2mortal(newSViv((IV)month)));
                PUSHs(sv_2mortal(newSViv((IV)day)));
                PUSHs(sv_2mortal(newSViv((IV)hour)));
                PUSHs(sv_2mortal(newSViv((IV)min)));
                PUSHs(sv_2mortal(newSViv((IV)sec)));
            }
            else DATECALC_DATE_ERROR;
        }
        else DATECALC_TIME_ERROR;
    }
    else DATECALC_DATE_ERROR;
}
#line 940 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_System_Clock); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_System_Clock)
{
    dXSARGS;
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 685 "Calc.xs"
{
    Z_int   year;
    Z_int   month;
    Z_int   day;
    Z_int   hour;
    Z_int   min;
    Z_int   sec;
    Z_int   doy;
    Z_int   dow;
    Z_int   dst;
    boolean gmt;

    if ((items == 0) or (items == 1))
    {
        if (items == 1) gmt = (boolean) SvIV( ST(0) );
        else            gmt = false;
        if (DateCalc_system_clock(&year,&month,&day,
                                  &hour,&min,&sec,
                                  &doy,&dow,&dst,
                                  gmt))
        {
            EXTEND(sp,9);
            PUSHs(sv_2mortal(newSViv((IV)year)));
            PUSHs(sv_2mortal(newSViv((IV)month)));
            PUSHs(sv_2mortal(newSViv((IV)day)));
            PUSHs(sv_2mortal(newSViv((IV)hour)));
            PUSHs(sv_2mortal(newSViv((IV)min)));
            PUSHs(sv_2mortal(newSViv((IV)sec)));
            PUSHs(sv_2mortal(newSViv((IV)doy)));
            PUSHs(sv_2mortal(newSViv((IV)dow)));
            PUSHs(sv_2mortal(newSViv((IV)dst)));
        }
        else DATECALC_SYSTEM_ERROR;
    }
    else croak("Usage: Date::Calc::System_Clock([gmt])");
}
#line 990 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Today); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Today)
{
    dXSARGS;
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 726 "Calc.xs"
{
    Z_int   year;
    Z_int   month;
    Z_int   day;
    Z_int   hour;
    Z_int   min;
    Z_int   sec;
    Z_int   doy;
    Z_int   dow;
    Z_int   dst;
    boolean gmt;

    if ((items == 0) or (items == 1))
    {
        if (items == 1) gmt = (boolean) SvIV( ST(0) );
        else            gmt = false;
        if (DateCalc_system_clock(&year,&month,&day,
                                  &hour,&min,&sec,
                                  &doy,&dow,&dst,
                                  gmt))
        {
            EXTEND(sp,3);
            PUSHs(sv_2mortal(newSViv((IV)year)));
            PUSHs(sv_2mortal(newSViv((IV)month)));
            PUSHs(sv_2mortal(newSViv((IV)day)));
        }
        else DATECALC_SYSTEM_ERROR;
    }
    else croak("Usage: Date::Calc::Today([gmt])");
}
#line 1034 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Now); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Now)
{
    dXSARGS;
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 761 "Calc.xs"
{
    Z_int   year;
    Z_int   month;
    Z_int   day;
    Z_int   hour;
    Z_int   min;
    Z_int   sec;
    Z_int   doy;
    Z_int   dow;
    Z_int   dst;
    boolean gmt;

    if ((items == 0) or (items == 1))
    {
        if (items == 1) gmt = (boolean) SvIV( ST(0) );
        else            gmt = false;
        if (DateCalc_system_clock(&year,&month,&day,
                                  &hour,&min,&sec,
                                  &doy,&dow,&dst,
                                  gmt))
        {
            EXTEND(sp,3);
            PUSHs(sv_2mortal(newSViv((IV)hour)));
            PUSHs(sv_2mortal(newSViv((IV)min)));
            PUSHs(sv_2mortal(newSViv((IV)sec)));
        }
        else DATECALC_SYSTEM_ERROR;
    }
    else croak("Usage: Date::Calc::Now([gmt])");
}
#line 1078 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Today_and_Now); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Today_and_Now)
{
    dXSARGS;
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 796 "Calc.xs"
{
    Z_int   year;
    Z_int   month;
    Z_int   day;
    Z_int   hour;
    Z_int   min;
    Z_int   sec;
    Z_int   doy;
    Z_int   dow;
    Z_int   dst;
    boolean gmt;

    if ((items == 0) or (items == 1))
    {
        if (items == 1) gmt = (boolean) SvIV( ST(0) );
        else            gmt = false;
        if (DateCalc_system_clock(&year,&month,&day,
                                  &hour,&min,&sec,
                                  &doy,&dow,&dst,
                                  gmt))
        {
            EXTEND(sp,6);
            PUSHs(sv_2mortal(newSViv((IV)year)));
            PUSHs(sv_2mortal(newSViv((IV)month)));
            PUSHs(sv_2mortal(newSViv((IV)day)));
            PUSHs(sv_2mortal(newSViv((IV)hour)));
            PUSHs(sv_2mortal(newSViv((IV)min)));
            PUSHs(sv_2mortal(newSViv((IV)sec)));
        }
        else DATECALC_SYSTEM_ERROR;
    }
    else croak("Usage: Date::Calc::Today_and_Now([gmt])");
}
#line 1125 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_This_Year); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_This_Year)
{
    dXSARGS;
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 834 "Calc.xs"
{
    Z_int   year;
    Z_int   month;
    Z_int   day;
    Z_int   hour;
    Z_int   min;
    Z_int   sec;
    Z_int   doy;
    Z_int   dow;
    Z_int   dst;
    boolean gmt;

    if ((items == 0) or (items == 1))
    {
        if (items == 1) gmt = (boolean) SvIV( ST(0) );
        else            gmt = false;
        if (DateCalc_system_clock(&year,&month,&day,
                                  &hour,&min,&sec,
                                  &doy,&dow,&dst,
                                  gmt))
        {
            EXTEND(sp,1);
            PUSHs(sv_2mortal(newSViv((IV)year)));
        }
        else DATECALC_SYSTEM_ERROR;
    }
    else croak("Usage: Date::Calc::This_Year([gmt])");
}
#line 1167 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Gmtime); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Gmtime)
{
    dXSARGS;
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 867 "Calc.xs"
{
#ifdef MACOS_TRADITIONAL
    double  f_seconds;
#endif
    time_t  seconds;
    Z_int   year;
    Z_int   month;
    Z_int   day;
    Z_int   hour;
    Z_int   min;
    Z_int   sec;
    Z_int   doy;
    Z_int   dow;
    Z_int   dst;

    if ((items == 0) or (items == 1))
    {
#ifdef MACOS_TRADITIONAL
        if (items == 1) f_seconds = (double) SvNV( ST(0) );
        else            f_seconds = (double) time(NULL);
        if ((f_seconds < 0) or (f_seconds > 0xFFFFFFFF))
            DATECALC_TIME_RANGE_ERROR;
        seconds = (time_t) f_seconds;
#else
        if (items == 1) seconds = (time_t) SvIV( ST(0) );
        else            seconds = time(NULL);
#endif
        if (DateCalc_gmtime(&year,&month,&day,
                            &hour,&min,&sec,
                            &doy,&dow,&dst,
                            seconds))
        {
            EXTEND(sp,9);
            PUSHs(sv_2mortal(newSViv((IV)year)));
            PUSHs(sv_2mortal(newSViv((IV)month)));
            PUSHs(sv_2mortal(newSViv((IV)day)));
            PUSHs(sv_2mortal(newSViv((IV)hour)));
            PUSHs(sv_2mortal(newSViv((IV)min)));
            PUSHs(sv_2mortal(newSViv((IV)sec)));
            PUSHs(sv_2mortal(newSViv((IV)doy)));
            PUSHs(sv_2mortal(newSViv((IV)dow)));
            PUSHs(sv_2mortal(newSViv((IV)dst)));
        }
        else DATECALC_TIME_RANGE_ERROR;
    }
    else croak("Usage: Date::Calc::Gmtime([time])");
}
#line 1228 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Localtime); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Localtime)
{
    dXSARGS;
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 919 "Calc.xs"
{
#ifdef MACOS_TRADITIONAL
    double  f_seconds;
#endif
    time_t  seconds;
    Z_int   year;
    Z_int   month;
    Z_int   day;
    Z_int   hour;
    Z_int   min;
    Z_int   sec;
    Z_int   doy;
    Z_int   dow;
    Z_int   dst;

    if ((items == 0) or (items == 1))
    {
#ifdef MACOS_TRADITIONAL
        if (items == 1) f_seconds = (double) SvNV( ST(0) );
        else            f_seconds = (double) time(NULL);
        if ((f_seconds < 0) or (f_seconds > 0xFFFFFFFF))
            DATECALC_TIME_RANGE_ERROR;
        seconds = (time_t) f_seconds;
#else
        if (items == 1) seconds = (time_t) SvIV( ST(0) );
        else            seconds = time(NULL);
#endif
        if (DateCalc_localtime(&year,&month,&day,
                               &hour,&min,&sec,
                               &doy,&dow,&dst,
                               seconds))
        {
            EXTEND(sp,9);
            PUSHs(sv_2mortal(newSViv((IV)year)));
            PUSHs(sv_2mortal(newSViv((IV)month)));
            PUSHs(sv_2mortal(newSViv((IV)day)));
            PUSHs(sv_2mortal(newSViv((IV)hour)));
            PUSHs(sv_2mortal(newSViv((IV)min)));
            PUSHs(sv_2mortal(newSViv((IV)sec)));
            PUSHs(sv_2mortal(newSViv((IV)doy)));
            PUSHs(sv_2mortal(newSViv((IV)dow)));
            PUSHs(sv_2mortal(newSViv((IV)dst)));
        }
        else DATECALC_TIME_RANGE_ERROR;
    }
    else croak("Usage: Date::Calc::Localtime([time])");
}
#line 1289 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Mktime); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Mktime)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: Date::Calc::Mktime(year, month, day, hour, min, sec)");
    SP -= items;
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
	Z_int	day = (Z_int)SvIV(ST(2));
	Z_int	hour = (Z_int)SvIV(ST(3));
	Z_int	min = (Z_int)SvIV(ST(4));
	Z_int	sec = (Z_int)SvIV(ST(5));
#line 977 "Calc.xs"
{
    time_t seconds;

    if (DateCalc_mktime(&seconds, year,month,day, hour,min,sec, -1,-1,-1))
    {
        EXTEND(sp,1);
#ifdef MACOS_TRADITIONAL
        PUSHs(sv_2mortal(newSVuv((UV)seconds)));
#else
        PUSHs(sv_2mortal(newSViv((IV)seconds)));
#endif
    }
    else DATECALC_DATE_RANGE_ERROR;
}
#line 1324 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Timezone); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Timezone)
{
    dXSARGS;
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 996 "Calc.xs"
{
#ifdef MACOS_TRADITIONAL
    double  f_when;
#endif
    time_t  when;
    Z_int   year;
    Z_int   month;
    Z_int   day;
    Z_int   hour;
    Z_int   min;
    Z_int   sec;
    Z_int   dst;

    if ((items == 0) or (items == 1))
    {
#ifdef MACOS_TRADITIONAL
        if (items == 1) f_when = (double) SvNV( ST(0) );
        else            f_when = (double) time(NULL);
        if ((f_when < 0) or (f_when > 0xFFFFFFFF))
            DATECALC_TIME_RANGE_ERROR;
        when = (time_t) f_when;
#else
        if (items == 1) when = (time_t) SvIV( ST(0) );
        else            when = time(NULL);
#endif
        if (DateCalc_timezone(&year,&month,&day,
                              &hour,&min,&sec,
                              &dst,when))
        {
            EXTEND(sp,7);
            PUSHs(sv_2mortal(newSViv((IV)year)));
            PUSHs(sv_2mortal(newSViv((IV)month)));
            PUSHs(sv_2mortal(newSViv((IV)day)));
            PUSHs(sv_2mortal(newSViv((IV)hour)));
            PUSHs(sv_2mortal(newSViv((IV)min)));
            PUSHs(sv_2mortal(newSViv((IV)sec)));
            PUSHs(sv_2mortal(newSViv((IV)dst)));
        }
        else DATECALC_TIME_RANGE_ERROR;
    }
    else croak("Usage: Date::Calc::Timezone([time])");
}
#line 1380 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Date_to_Time); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Date_to_Time)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: Date::Calc::Date_to_Time(year, month, day, hour, min, sec)");
    SP -= items;
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
	Z_int	day = (Z_int)SvIV(ST(2));
	Z_int	hour = (Z_int)SvIV(ST(3));
	Z_int	min = (Z_int)SvIV(ST(4));
	Z_int	sec = (Z_int)SvIV(ST(5));
#line 1049 "Calc.xs"
{
    time_t seconds;

    if (DateCalc_date2time(&seconds, year,month,day, hour,min,sec))
    {
        EXTEND(sp,1);
#ifdef MACOS_TRADITIONAL
        PUSHs(sv_2mortal(newSVuv((UV)seconds)));
#else
        PUSHs(sv_2mortal(newSViv((IV)seconds)));
#endif
    }
    else DATECALC_DATE_RANGE_ERROR;
}
#line 1415 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Time_to_Date); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Time_to_Date)
{
    dXSARGS;
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1068 "Calc.xs"
{
#ifdef MACOS_TRADITIONAL
    double  f_seconds;
#endif
    time_t  seconds;
    Z_int   year;
    Z_int   month;
    Z_int   day;
    Z_int   hour;
    Z_int   min;
    Z_int   sec;

    if ((items == 0) or (items == 1))
    {
#ifdef MACOS_TRADITIONAL
        if (items == 1) f_seconds = (double) SvNV( ST(0) );
        else            f_seconds = (double) time(NULL);
        if ((f_seconds < 0) or (f_seconds > 0xFFFFFFFF))
            DATECALC_TIME_RANGE_ERROR;
        seconds = (time_t) f_seconds;
#else
        if (items == 1) seconds = (time_t) SvIV( ST(0) );
        else            seconds = time(NULL);
#endif
        if (DateCalc_time2date(&year,&month,&day, &hour,&min,&sec, seconds))
        {
            EXTEND(sp,6);
            PUSHs(sv_2mortal(newSViv((IV)year)));
            PUSHs(sv_2mortal(newSViv((IV)month)));
            PUSHs(sv_2mortal(newSViv((IV)day)));
            PUSHs(sv_2mortal(newSViv((IV)hour)));
            PUSHs(sv_2mortal(newSViv((IV)min)));
            PUSHs(sv_2mortal(newSViv((IV)sec)));
        }
        else DATECALC_TIME_RANGE_ERROR;
    }
    else croak("Usage: Date::Calc::Time_to_Date([time])");
}
#line 1467 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Easter_Sunday); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Easter_Sunday)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::Easter_Sunday(year)");
    SP -= items;
    {
	Z_int	year = (Z_int)SvIV(ST(0));
#line 1112 "Calc.xs"
{
    Z_int month;
    Z_int day;

    if ((year > 0) and DateCalc_easter_sunday(&year,&month,&day))
    {
        EXTEND(sp,3);
        PUSHs(sv_2mortal(newSViv((IV)year)));
        PUSHs(sv_2mortal(newSViv((IV)month)));
        PUSHs(sv_2mortal(newSViv((IV)day)));
    }
    else DATECALC_YEAR_ERROR;
}
#line 1496 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Decode_Month); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Decode_Month)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::Decode_Month(string)");
    {
	charptr	string = (charptr)SvPV_nolen(ST(0));
	Z_int	RETVAL;
	dXSTARG;
#line 1131 "Calc.xs"
{
    RETVAL = DateCalc_Decode_Month(string,strlen((char *)string));
}
#line 1516 "Calc.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_Decode_Day_of_Week); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Decode_Day_of_Week)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::Decode_Day_of_Week(string)");
    {
	charptr	string = (charptr)SvPV_nolen(ST(0));
	Z_int	RETVAL;
	dXSTARG;
#line 1142 "Calc.xs"
{
    RETVAL = DateCalc_Decode_Day_of_Week(string,strlen((char *)string));
}
#line 1536 "Calc.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_Decode_Language); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Decode_Language)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::Decode_Language(string)");
    {
	charptr	string = (charptr)SvPV_nolen(ST(0));
	Z_int	RETVAL;
	dXSTARG;
#line 1153 "Calc.xs"
{
    RETVAL = DateCalc_Decode_Language(string,strlen((char *)string));
}
#line 1556 "Calc.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_Decode_Date_EU); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Decode_Date_EU)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::Decode_Date_EU(string)");
    SP -= items;
    {
	charptr	string = (charptr)SvPV_nolen(ST(0));
#line 1164 "Calc.xs"
{
    Z_int year;
    Z_int month;
    Z_int day;

    if (DateCalc_decode_date_eu(string,&year,&month,&day))
    {
        EXTEND(sp,3);
        PUSHs(sv_2mortal(newSViv((IV)year)));
        PUSHs(sv_2mortal(newSViv((IV)month)));
        PUSHs(sv_2mortal(newSViv((IV)day)));
    }
    /* else return empty list */
}
#line 1586 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Decode_Date_US); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Decode_Date_US)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::Decode_Date_US(string)");
    SP -= items;
    {
	charptr	string = (charptr)SvPV_nolen(ST(0));
#line 1184 "Calc.xs"
{
    Z_int year;
    Z_int month;
    Z_int day;

    if (DateCalc_decode_date_us(string,&year,&month,&day))
    {
        EXTEND(sp,3);
        PUSHs(sv_2mortal(newSViv((IV)year)));
        PUSHs(sv_2mortal(newSViv((IV)month)));
        PUSHs(sv_2mortal(newSViv((IV)day)));
    }
    /* else return empty list */
}
#line 1616 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Fixed_Window); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Fixed_Window)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::Fixed_Window(year)");
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	RETVAL;
	dXSTARG;

	RETVAL = DateCalc_Fixed_Window(year);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_Moving_Window); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Moving_Window)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::Moving_Window(year)");
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	RETVAL;
	dXSTARG;

	RETVAL = DateCalc_Moving_Window(year);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_Compress); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Compress)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Calc::Compress(year, month, day)");
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
	Z_int	day = (Z_int)SvIV(ST(2));
	Z_int	RETVAL;
	dXSTARG;

	RETVAL = DateCalc_Compress(year, month, day);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_Uncompress); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Uncompress)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::Uncompress(date)");
    SP -= items;
    {
	Z_int	date = (Z_int)SvIV(ST(0));
#line 1221 "Calc.xs"
{
    Z_int century;
    Z_int year;
    Z_int month;
    Z_int day;

    if (DateCalc_uncompress(date,&century,&year,&month,&day))
    {
        EXTEND(sp,4);
        PUSHs(sv_2mortal(newSViv((IV)century)));
        PUSHs(sv_2mortal(newSViv((IV)year)));
        PUSHs(sv_2mortal(newSViv((IV)month)));
        PUSHs(sv_2mortal(newSViv((IV)day)));
    }
    /* else return empty list */
    /* else DATECALC_DATE_ERROR; */
}
#line 1702 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_check_compressed); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_check_compressed)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::check_compressed(date)");
    {
	Z_int	date = (Z_int)SvIV(ST(0));
	boolean	RETVAL;
	dXSTARG;

	RETVAL = DateCalc_check_compressed(date);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_Compressed_to_Text); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Compressed_to_Text)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::Compressed_to_Text(date)");
    SP -= items;
    {
	Z_int	date = (Z_int)SvIV(ST(0));
#line 1249 "Calc.xs"
{
    charptr string;

    string = DateCalc_Compressed_to_Text(date);
    if (string != NULL)
    {
        EXTEND(sp,1);
        PUSHs(sv_2mortal(newSVpv((char *)string,0)));
        DateCalc_Dispose(string);
    }
    else DATECALC_MEMORY_ERROR;
}
#line 1747 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Date_to_Text); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Date_to_Text)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Calc::Date_to_Text(year, month, day)");
    SP -= items;
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
	Z_int	day = (Z_int)SvIV(ST(2));
#line 1269 "Calc.xs"
{
    charptr string;

    if (DateCalc_check_date(year,month,day))
    {
        string = DateCalc_Date_to_Text(year,month,day);
        if (string != NULL)
        {
            EXTEND(sp,1);
            PUSHs(sv_2mortal(newSVpv((char *)string,0)));
            DateCalc_Dispose(string);
        }
        else DATECALC_MEMORY_ERROR;
    }
    else DATECALC_DATE_ERROR;
}
#line 1781 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Date_to_Text_Long); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Date_to_Text_Long)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Calc::Date_to_Text_Long(year, month, day)");
    SP -= items;
    {
	Z_int	year = (Z_int)SvIV(ST(0));
	Z_int	month = (Z_int)SvIV(ST(1));
	Z_int	day = (Z_int)SvIV(ST(2));
#line 1293 "Calc.xs"
{
    charptr string;

    if (DateCalc_check_date(year,month,day))
    {
        string = DateCalc_Date_to_Text_Long(year,month,day);
        if (string != NULL)
        {
            EXTEND(sp,1);
            PUSHs(sv_2mortal(newSVpv((char *)string,0)));
            DateCalc_Dispose(string);
        }
        else DATECALC_MEMORY_ERROR;
    }
    else DATECALC_DATE_ERROR;
}
#line 1815 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_English_Ordinal); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_English_Ordinal)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::English_Ordinal(number)");
    SP -= items;
    {
	Z_int	number = (Z_int)SvIV(ST(0));
#line 1315 "Calc.xs"
{
    blockdef(string,64);

    DateCalc_English_Ordinal(string,number);
    EXTEND(sp,1);
    PUSHs(sv_2mortal(newSVpv((char *)string,0)));
}
#line 1838 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Calendar); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Calendar)
{
    dXSARGS;
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1327 "Calc.xs"
{
    Z_int   year;
    Z_int   month;
    boolean orthodox;
    charptr string;

    if ((items >= 2) and (items <= 3))
    {
        year  = (Z_int) SvIV( ST(0) );
        month = (Z_int) SvIV( ST(1) );
        if (items == 3) orthodox = (boolean) SvIV( ST(2) );
        else            orthodox = false;
        if (year > 0)
        {
            if ((month >= 1) and (month <= 12))
            {
                string = DateCalc_Calendar(year,month,orthodox);
                if (string != NULL)
                {
                    EXTEND(sp,1);
                    PUSHs(sv_2mortal(newSVpv((char *)string,0)));
                    DateCalc_Dispose(string);
                }
                else DATECALC_MEMORY_ERROR;
            }
            else DATECALC_MONTH_ERROR;
        }
        else DATECALC_YEAR_ERROR;
    }
    else croak("Usage: Date::Calc::Calendar(year,month[,orthodox])");
}
#line 1883 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Month_to_Text); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Month_to_Text)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::Month_to_Text(month)");
    SP -= items;
    {
	Z_int	month = (Z_int)SvIV(ST(0));
#line 1364 "Calc.xs"
{
    if ((month >= 1) and (month <= 12))
    {
        EXTEND(sp,1);
        PUSHs(sv_2mortal(newSVpv((char *)DateCalc_Month_to_Text_[DateCalc_Language][month],0)));
    }
    else DATECALC_MONTH_ERROR;
}
#line 1907 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Day_of_Week_to_Text); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Day_of_Week_to_Text)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::Day_of_Week_to_Text(dow)");
    SP -= items;
    {
	Z_int	dow = (Z_int)SvIV(ST(0));
#line 1378 "Calc.xs"
{
    if ((dow >= 1) and (dow <= 7))
    {
        EXTEND(sp,1);
        PUSHs(sv_2mortal(newSVpv((char *)DateCalc_Day_of_Week_to_Text_[DateCalc_Language][dow],0)));
    }
    else DATECALC_DAYOFWEEK_ERROR;
}
#line 1931 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Day_of_Week_Abbreviation); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Day_of_Week_Abbreviation)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::Day_of_Week_Abbreviation(dow)");
    SP -= items;
    {
	Z_int	dow = (Z_int)SvIV(ST(0));
#line 1392 "Calc.xs"
{
    blockdef(buffer,4);

    if ((dow >= 1) and (dow <= 7))
    {
        EXTEND(sp,1);
        if (DateCalc_Day_of_Week_Abbreviation_[DateCalc_Language][0][0] != '\0')
        {
            PUSHs(sv_2mortal(newSVpv((char *)DateCalc_Day_of_Week_Abbreviation_[DateCalc_Language][dow],0)));
        }
        else
        {
            strncpy((char *)buffer,(char *)DateCalc_Day_of_Week_to_Text_[DateCalc_Language][dow],3);
            buffer[3] = '\0';
            PUSHs(sv_2mortal(newSVpv((char *)buffer,0)));
        }
    }
    else DATECALC_DAYOFWEEK_ERROR;
}
#line 1966 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Language_to_Text); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Language_to_Text)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::Language_to_Text(lang)");
    SP -= items;
    {
	Z_int	lang = (Z_int)SvIV(ST(0));
#line 1417 "Calc.xs"
{
    if ((lang >= 1) and (lang <= DateCalc_LANGUAGES))
    {
        EXTEND(sp,1);
        PUSHs(sv_2mortal(newSVpv((char *)DateCalc_Language_to_Text_[lang],0)));
    }
    else DATECALC_LANGUAGE_ERROR;
}
#line 1990 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Language); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Language)
{
    dXSARGS;
    {
	Z_int	RETVAL;
	dXSTARG;
#line 1430 "Calc.xs"
{
    Z_int lang;

    if ((items >= 0) and (items <= 1))
    {
        RETVAL = DateCalc_Language;
        if (items == 1)
        {
            lang = (Z_int) SvIV( ST(0) );
            if ((lang >= 1) and (lang <= DateCalc_LANGUAGES))
            {
                DateCalc_Language = lang;
            }
            else DATECALC_LANGUAGE_ERROR;
        }
    }
    else croak("Usage: Date::Calc::Language([lang])");
}
#line 2022 "Calc.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_Languages); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Languages)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Date::Calc::Languages()");
    {
	Z_int	RETVAL;
	dXSTARG;
#line 1455 "Calc.xs"
{
    RETVAL = DateCalc_LANGUAGES;
}
#line 2041 "Calc.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Calc_ISO_LC); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_ISO_LC)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::ISO_LC(scalar)");
    SP -= items;
    {
	SV *	scalar = ST(0);
#line 1466 "Calc.xs"
{
    charptr string;
    charptr buffer;
    N_int length;
    N_int index;

    if ( DATECALC_STRING(scalar,string,length) )
    {
        buffer = (charptr) malloc(length+1);
        if (buffer != NULL)
        {
            for ( index = 0; index < length; index++ )
                buffer[index] = DateCalc_ISO_LC(string[index]);
            buffer[length] = '\0';
            EXTEND(sp,1);
            PUSHs(sv_2mortal(newSVpv((char *)buffer,length)));
            free(buffer);
        }
        else DATECALC_MEMORY_ERROR;
    }
    else DATECALC_STRING_ERROR;
}
#line 2079 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_ISO_UC); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_ISO_UC)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Calc::ISO_UC(scalar)");
    SP -= items;
    {
	SV *	scalar = ST(0);
#line 1494 "Calc.xs"
{
    charptr string;
    charptr buffer;
    N_int length;
    N_int index;

    if ( DATECALC_STRING(scalar,string,length) )
    {
        buffer = (charptr) malloc(length+1);
        if (buffer != NULL)
        {
            for ( index = 0; index < length; index++ )
                buffer[index] = DateCalc_ISO_UC(string[index]);
            buffer[length] = '\0';
            EXTEND(sp,1);
            PUSHs(sv_2mortal(newSVpv((char *)buffer,length)));
            free(buffer);
        }
        else DATECALC_MEMORY_ERROR;
    }
    else DATECALC_STRING_ERROR;
}
#line 2117 "Calc.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Calc_Version); /* prototype to pass -Wmissing-prototypes */
XS(XS_Date__Calc_Version)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Date::Calc::Version()");
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1521 "Calc.xs"
{
    charptr string;

    string = DateCalc_Version();
    if (string != NULL)
    {
        EXTEND(sp,1);
        PUSHs(sv_2mortal(newSVpv((char *)string,0)));
    }
    else DATECALC_MEMORY_ERROR;
}
#line 2144 "Calc.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Date__Calc); /* prototype to pass -Wmissing-prototypes */
XS(boot_Date__Calc)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Date::Calc::Days_in_Year", XS_Date__Calc_Days_in_Year, file);
        newXS("Date::Calc::Days_in_Month", XS_Date__Calc_Days_in_Month, file);
        newXS("Date::Calc::Weeks_in_Year", XS_Date__Calc_Weeks_in_Year, file);
        newXS("Date::Calc::leap_year", XS_Date__Calc_leap_year, file);
        newXS("Date::Calc::check_date", XS_Date__Calc_check_date, file);
        newXS("Date::Calc::check_time", XS_Date__Calc_check_time, file);
        newXS("Date::Calc::check_business_date", XS_Date__Calc_check_business_date, file);
        newXS("Date::Calc::Day_of_Year", XS_Date__Calc_Day_of_Year, file);
        newXS("Date::Calc::Date_to_Days", XS_Date__Calc_Date_to_Days, file);
        newXS("Date::Calc::Day_of_Week", XS_Date__Calc_Day_of_Week, file);
        newXS("Date::Calc::Week_Number", XS_Date__Calc_Week_Number, file);
        newXS("Date::Calc::Week_of_Year", XS_Date__Calc_Week_of_Year, file);
        newXS("Date::Calc::Monday_of_Week", XS_Date__Calc_Monday_of_Week, file);
        newXS("Date::Calc::Nth_Weekday_of_Month_Year", XS_Date__Calc_Nth_Weekday_of_Month_Year, file);
        newXS("Date::Calc::Standard_to_Business", XS_Date__Calc_Standard_to_Business, file);
        newXS("Date::Calc::Business_to_Standard", XS_Date__Calc_Business_to_Standard, file);
        newXS("Date::Calc::Delta_Days", XS_Date__Calc_Delta_Days, file);
        newXS("Date::Calc::Delta_DHMS", XS_Date__Calc_Delta_DHMS, file);
        newXS("Date::Calc::Delta_YMD", XS_Date__Calc_Delta_YMD, file);
        newXS("Date::Calc::Delta_YMDHMS", XS_Date__Calc_Delta_YMDHMS, file);
        newXS("Date::Calc::Normalize_DHMS", XS_Date__Calc_Normalize_DHMS, file);
        newXS("Date::Calc::Add_Delta_Days", XS_Date__Calc_Add_Delta_Days, file);
        newXS("Date::Calc::Add_Delta_DHMS", XS_Date__Calc_Add_Delta_DHMS, file);
        newXS("Date::Calc::Add_Delta_YM", XS_Date__Calc_Add_Delta_YM, file);
        newXS("Date::Calc::Add_Delta_YMD", XS_Date__Calc_Add_Delta_YMD, file);
        newXS("Date::Calc::Add_Delta_YMDHMS", XS_Date__Calc_Add_Delta_YMDHMS, file);
        newXS("Date::Calc::System_Clock", XS_Date__Calc_System_Clock, file);
        newXS("Date::Calc::Today", XS_Date__Calc_Today, file);
        newXS("Date::Calc::Now", XS_Date__Calc_Now, file);
        newXS("Date::Calc::Today_and_Now", XS_Date__Calc_Today_and_Now, file);
        newXS("Date::Calc::This_Year", XS_Date__Calc_This_Year, file);
        newXS("Date::Calc::Gmtime", XS_Date__Calc_Gmtime, file);
        newXS("Date::Calc::Localtime", XS_Date__Calc_Localtime, file);
        newXS("Date::Calc::Mktime", XS_Date__Calc_Mktime, file);
        newXS("Date::Calc::Timezone", XS_Date__Calc_Timezone, file);
        newXS("Date::Calc::Date_to_Time", XS_Date__Calc_Date_to_Time, file);
        newXS("Date::Calc::Time_to_Date", XS_Date__Calc_Time_to_Date, file);
        newXS("Date::Calc::Easter_Sunday", XS_Date__Calc_Easter_Sunday, file);
        newXS("Date::Calc::Decode_Month", XS_Date__Calc_Decode_Month, file);
        newXS("Date::Calc::Decode_Day_of_Week", XS_Date__Calc_Decode_Day_of_Week, file);
        newXS("Date::Calc::Decode_Language", XS_Date__Calc_Decode_Language, file);
        newXS("Date::Calc::Decode_Date_EU", XS_Date__Calc_Decode_Date_EU, file);
        newXS("Date::Calc::Decode_Date_US", XS_Date__Calc_Decode_Date_US, file);
        newXS("Date::Calc::Fixed_Window", XS_Date__Calc_Fixed_Window, file);
        newXS("Date::Calc::Moving_Window", XS_Date__Calc_Moving_Window, file);
        newXS("Date::Calc::Compress", XS_Date__Calc_Compress, file);
        newXS("Date::Calc::Uncompress", XS_Date__Calc_Uncompress, file);
        newXS("Date::Calc::check_compressed", XS_Date__Calc_check_compressed, file);
        newXS("Date::Calc::Compressed_to_Text", XS_Date__Calc_Compressed_to_Text, file);
        newXS("Date::Calc::Date_to_Text", XS_Date__Calc_Date_to_Text, file);
        newXS("Date::Calc::Date_to_Text_Long", XS_Date__Calc_Date_to_Text_Long, file);
        newXS("Date::Calc::English_Ordinal", XS_Date__Calc_English_Ordinal, file);
        newXS("Date::Calc::Calendar", XS_Date__Calc_Calendar, file);
        newXS("Date::Calc::Month_to_Text", XS_Date__Calc_Month_to_Text, file);
        newXS("Date::Calc::Day_of_Week_to_Text", XS_Date__Calc_Day_of_Week_to_Text, file);
        newXS("Date::Calc::Day_of_Week_Abbreviation", XS_Date__Calc_Day_of_Week_Abbreviation, file);
        newXS("Date::Calc::Language_to_Text", XS_Date__Calc_Language_to_Text, file);
        newXS("Date::Calc::Language", XS_Date__Calc_Language, file);
        newXS("Date::Calc::Languages", XS_Date__Calc_Languages, file);
        newXS("Date::Calc::ISO_LC", XS_Date__Calc_ISO_LC, file);
        newXS("Date::Calc::ISO_UC", XS_Date__Calc_ISO_UC, file);
        newXS("Date::Calc::Version", XS_Date__Calc_Version, file);
    XSRETURN_YES;
}

