## -*- Mode: awk -*-
## Title:  extract.by.account_num
##
## Doc: /home/fxc/project/NTL/programs/Awk/extract.by.account_num.awk
## Original Author:     Fei Chen  <fxc@production1.fairisaac.com>
## Created:             Thu Dec 11 2003
##
## $Header$
##
## $Log$
##
## $Id$
########################################################


BEGIN{
# generated by
# cfg=/home/fxc/project/NTL/ux58//field,length
# cat $cfg | awk "BEGIN{printf(\"FIELDWIDTHS = \\\"\")}{printf(\" %d \", \$2)}END{printf(\"\\\"\")}"

# make up a random array for testing
# zcat NTL_FM_DATA/NTLConsortium2003_032_2217.gz  | awk "BEGIN{            $(cat $cfg | awk "BEGIN{printf(\"FIELDWIDTHS = \\\"\")}{printf(\" %d \", \$2)}END{printf(\"\\\"\")}")                                                           }{ print \$3; }" | awk '{printf("array[\"%-24s\"]=\"%s\";\n",$1,"random")}' M

 if(prefix == "")
   exit;


  set_fraud_array();
  FIELDWIDTHS = " 1  4  24  24  8  6  16  2  1  5  5  5  5  1  1  1  24  24  32  24  3  1  16  3  3  5  5  5  8  6  10  8  6  1  1  1  1  1  4  1  24  24 ";

 fraud = 1;
 notfraud = 1;
 unconfirmed = 1;
 random = 1;


 print "initialization done";

}
{
  acct = $3;
  if(acct in array)
    {
      v = array[acct];

      if(v == "Random")
	random ++;
      else if(v == "Fraud")
	fraud ++;
      else if(v == "NotFraud")
	notfraud ++;
      else if(v == "UnConfirmed")
	unconfirmed ++;

      fn = "/tmp/fxc/" prefix "_" array[acct];
      print $0 > fn;
    }

  at = 500000;

  if(NR % at == 0)
    printf("%d:%-8d: random=%-5d unconfirmed=%-5d notfraud=%-5d fraud=%-5d\n", filenum, NR , random, unconfirmed, notfraud, fraud);

#  print_freqently_at(random, NR, at, "Random");
#  print_freqently_at(fraud, NR, at, "Fraud");
#  print_freqently_at(notfraud, NR, at, "NotFraud");
#  print_freqently_at(unconfirmed, NR, at, "UnConfirmed");

}
END{
  if(prefix == "")
    {
      print "-v prefix=XX for output file name is required";
      exit;
    }
  fn = "/tmp/fxc/" prefix "_" "NumberFound";
  print "Random", random-1 > fn;
  print "Fraud", fraud-1 > fn;
  print "NotFraud", notfraud-1 > fn;
  print "UnConfirmed", unconfirmed-1 > fn;
}


function print_freqently_at(x, counter, at, label)
{
  # print x and label at a rate of "at"
  if(counter % at == 0)
    printf("%s: %15s %d\n", counter , label, x);
}
