#!/usr/local/bin/bash

usage()
{
echo "Usage: $0 cards.dat.gz"
exit 1
}

HIST="histogram.pl"
CUT="ufalcut"
ANALY="analysis"
ZNL="znl"

[ $# -eq 1 ] || usage;
[ -d $ANALY ] || mkdir $ANALY

if [[ $1 == *.gz ]]; then 
  CMD="gzip -dc $1"
else
  CMD="cat $1"
fi

echo "#GENERAL CHECKS:" >$ANALY/card.gen
echo "####################################################################" >>$ANALY/card.gen
nor=`$ZNL $1 |awk '{print $1}'` 
echo "1. Number of records:  $nor" >>$ANALY/card.gen
rl=`$CMD |head -1 |wc -c`
echo "2. Record length:      $rl" >>$ANALY/card.gen
if ($CMD |is_sort -c1-19,91-98 &>/dev/null); then
st="Yes!"
else
st="No!!!"
fi
echo "3. Is sorted?          $st" >>$ANALY/card.gen
echo "4. Hash value histogram" >>$ANALY/card.gen
$CMD | $CUT -c1-19 |getHashValues -s |$HIST >>$ANALY/card.gen
#card.issue-date
fl=card.issue-date
	$CMD  | $CUT -c40-45 \
	| $HIST > $ANALY/$fl.hist

#card.postal-code
fl=card.postal-code
	$CMD  | $CUT -c20-24 \
	| $HIST > $ANALY/$fl.hist

#card.zip3
fl=card.zip3
	$CMD  | $CUT -c20-22 \
	| $HIST > $ANALY/$fl.hist

#card.cntry
fl=card.cntry
	$CMD  | $CUT -c29-31 \
	| $HIST > $ANALY/$fl.hist

#card.open-date
fl=card.open-date
	$CMD  | $CUT -c32-37 \
	| $HIST > $ANALY/$fl.hist

#card.issue-type
fl=card.issue-type
	$CMD  | $CUT -c48 \
	| $HIST > $ANALY/$fl.hist

#card.expire-date
fl=card.expire-date
	$CMD  | $CUT -c49-54 \
	| $HIST > $ANALY/$fl.hist

#card.type
fl=card.type
	$CMD  | $CUT -c86 \
	| $HIST > $ANALY/$fl.hist

#card.use
fl=card.use
	$CMD  | $CUT -c87 \
	| $HIST > $ANALY/$fl.hist

#card.num-cards
fl=card.num-cards
	$CMD  | $CUT -c88-90 \
	| $HIST > $ANALY/$fl.hist

#card.rec-date
fl=card.rec-date
	$CMD  | $CUT -c91-98 \
	| $HIST > $ANALY/$fl.hist

#card.portfolio
if [ $rl -ge 200 ]; then
fl=card.portfolio
	$CMD  | $CUT -c187-200 \
	| $HIST > $ANALY/$fl.hist
fi
