/*
 * This file was generated automatically by xsubpp version 1.9507 from the 
 * contents of Simple.xs. Do not edit this file, edit Simple.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Simple.xs"
#define PERL_POLLUTE

#include <EXTERN.h>
#include <perl.h>
#include <XSUB.h>


static UV dim[14]
	= { 31, 0, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31, 31, 28 };
static IV tweak[12]
	= { 1, 2, 4, 5, 7, 8, 9, 11, 12, 14, 15, 16 };
static IV cum_days[12]
	= { -1, 30, 58, 89, 119, 150, 180, 211, 242, 272, 303, 333 };

static bool
is_leap_year (IV y)
{
	return (y % 4 == 0) && ((y % 100 != 0) || (y % 400 == 0));
}

static IV
days_in_month (IV month, IV year)
{
	IV ret = dim [ month - 1 ];
	if (ret == 0)
		ret = is_leap_year (year) ? 29 : 28;
	return ret;
}

/* Compute the number of days since 1970.  */
static bool
ymd_to_days (IV y, IV m, IV d, IV* days)
{
	IV x;
	IV nonleap_days;
	IV leap_days_4;
	IV leap_holes_100;
	IV leap_days_400;

	if (m < 1 || m > 12 || d < 1 || (d > 28 && d > days_in_month (m, y)))
		return FALSE;

	x = (m <= 2 ? y - 1 : y);
	nonleap_days = d + cum_days [m - 1] + 365 * (y - 1970);

	leap_days_4 = (x - 1968) >> 2;
	if (x >= 1900)
		leap_holes_100 = (x - 1900) / 100;
	else
		leap_holes_100 = - (1900 - x) / 100;
	if (x >= 1600)
		leap_days_400 = (x - 1600) / 400;
	else
		leap_days_400 = - (1600 - x) / 400;

	*days = nonleap_days + leap_days_4 - leap_holes_100 + leap_days_400;
	return TRUE;
}

/* Compute year, month, and day given days_since_1970.  */
static void
days_to_ymd (IV days, IV ymd[3])
{
	IV year;
	IV month, day, quot;

	/* Shift frame of reference from 1 Jan 1970 to (the imaginary)
	   1 Mar 0AD.  */
	days += 719468;

	/* Do the math.  */

	quot = days / 146097;
	days -= 146097 * quot;
	year = 400 * quot;

	if (days == 146096)
	{
		/* Handle 29 Feb 2000, 2400, ...  */
		year += 400;
		month = 2;
		day = 29;
	}
	else
	{
		quot = days / 36524;
		days -= 36524 * quot;
		year += 100 * quot;

		quot = days / 1461;
		days -= 1461 * quot;
		year += 4 * quot;

		if (days == 1460)
		{
			year += 4;
			month = 2;
			day = 29;
		}
		else
		{
			quot = days / 365;
			days -= 365 * quot;
			year += quot;

			quot = days / 32;
			days -= 32 * quot;
			month = quot;

			day = days + tweak [month];
			days = dim [month + 2];

			if (day > days)
			{
				day -= days;
				month += 1;
			}
			if (month > 9)
			{
				month -= 9;
				year += 1;
			}
			else
				month += 3;
		}
	}
	ymd[0] = year;
	ymd[1] = month;
	ymd[2] = day;
}

static bool
d8_to_days (SV* d8, IV* days)
{
	char buf[5];
	STRLEN len;
	char* p;

	p = SvPV(d8, len);
	if (len == 8)
	{
		while (len > 0)
		{
			if (!isDIGIT(p[len - 1]))
				break;
			len--;
		}
		if (len != 0)
			return FALSE;
	}
	else
		return FALSE;

	return ymd_to_days(10*(10*(10*(p[0]-'0')+p[1]-'0')+p[2]-'0')+p[3]-'0',
			   10*(p[4]-'0')+p[5]-'0', 10*(p[6]-'0')+p[7]-'0',
			   days);
}

static SV*
days_to_date (IV days, const char* pkg)
{
	return sv_bless (newRV_noinc (newSViv (days)),
			 gv_stashpv (pkg == 0 ? "Date::Simple" : pkg, 1));
}

static int
is_object (SV* sv)
{
	return (SvROK (sv) && SvTYPE (SvRV (sv)) == SVt_PVMG);
}

static SV*
new_for_cmp (SV* left, SV* right, int croak_on_fail)
{
	dSP;
	SV* ret;

	/* Comparing date with non-date.
	   Try to convert the right side to a date.  */
	EXTEND (sp, 2);
	PUSHMARK(sp);
	PUSHs (left);
	PUSHs (right);
	PUTBACK;
	perl_call_method (croak_on_fail ? "new" : "_new", G_SCALAR);
	SPAGAIN;
	ret = POPs;
	if (croak_on_fail && ! is_object (ret))
	{
		PUSHMARK(sp);
		PUSHs (left);
		PUSHs (right);
		PUTBACK;
		perl_call_pv ("Date::Simple::_inval", G_VOID);
		SPAGAIN;
	}
	return ret;
}



#line 212 "Simple.c"
XS(XS_Date__Simple_ymd)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Simple::ymd(y, m, d)");
    {
	IV	y = (IV)SvIV(ST(0));
	IV	m = (IV)SvIV(ST(1));
	IV	d = (IV)SvIV(ST(2));
	SV *	RETVAL;
#line 210 "Simple.xs"
	{
		IV days;
		if (ymd_to_days (y, m, d, &days))
			RETVAL = days_to_date (days, 0);
		else
			XSRETURN_UNDEF;
	}
#line 231 "Simple.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Date__Simple_d8)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Simple::d8(d8)");
    {
	SV*	d8 = ST(0);
	SV *	RETVAL;
#line 224 "Simple.xs"
	{
		IV days;
		if (d8_to_days (d8, &days))
			RETVAL = days_to_date (days, 0);
		else
			XSRETURN_UNDEF;
	}
#line 254 "Simple.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Date__Simple_leap_year)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Simple::leap_year(y)");
    {
	IV	y = (IV)SvIV(ST(0));
	bool	RETVAL;
#line 238 "Simple.xs"
	{
		RETVAL = is_leap_year (y);
	}
#line 273 "Simple.c"
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Date__Simple_days_in_month)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Date::Simple::days_in_month(y, m)");
    {
	IV	y = (IV)SvIV(ST(0));
	IV	m = (IV)SvIV(ST(1));
	IV	RETVAL;
	dXSTARG;
#line 249 "Simple.xs"
	{
		if (m < 1 || m > 12)
			croak ("days_in_month: month out of range (%d)",
			       (int) m);
		RETVAL = days_in_month (m, y);
	}
#line 297 "Simple.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Simple_validate)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Simple::validate(ysv, m, d)");
    {
	SV*	ysv = ST(0);
	IV	m = (IV)SvIV(ST(1));
	IV	d = (IV)SvIV(ST(2));
	IV	RETVAL;
	dXSTARG;
#line 264 "Simple.xs"
	{
		IV y;
		y = SvIV (ysv);
		if ((IV) SvNV (ysv) != y)
			RETVAL = 0;
		else if (m < 1 || m > 12)
			RETVAL = 0;
		else if (d < 1 || d > days_in_month (m, y))
			RETVAL = 0;
		else
			RETVAL = 1;
	}
#line 327 "Simple.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Simple_ymd_to_days)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Simple::ymd_to_days(y, m, d)");
    {
	IV	y = (IV)SvIV(ST(0));
	IV	m = (IV)SvIV(ST(1));
	IV	d = (IV)SvIV(ST(2));
#line 285 "Simple.xs"
	{
		IV days;
		if (! ymd_to_days (y, m, d, &days))
			XSRETURN_UNDEF;
		else
			XSRETURN_IV (days);
	}
#line 350 "Simple.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Date__Simple_days_since_1970)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Simple::days_since_1970(date)");
    {
	SV*	date = ST(0);
	SV *	RETVAL;
#line 297 "Simple.xs"
	{
		if (SvROK(date))
			RETVAL = SvREFCNT_inc (SvRV(date));
		else
			XSRETURN_UNDEF;
	}
#line 370 "Simple.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Date__Simple_days_to_ymd)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Simple::days_to_ymd(days)");
    SP -= items;
    {
	IV	days = (IV)SvIV(ST(0));
#line 310 "Simple.xs"
	{
		IV ymd[3];
		days_to_ymd (days, ymd);
		EXTEND (sp, 3);
		PUSHs (sv_2mortal (newSViv (ymd[0])));
		PUSHs (sv_2mortal (newSViv (ymd[1])));
		PUSHs (sv_2mortal (newSViv (ymd[2])));
	}
#line 394 "Simple.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Simple_year)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Simple::year(date)");
    {
	SV*	date = ST(0);
	IV	RETVAL;
	dXSTARG;
#line 323 "Simple.xs"
	{
		IV ymd[3];
		if (! SvROK (date))
			XSRETURN_UNDEF;

		days_to_ymd (SvIV (SvRV (date)), ymd);
		RETVAL = ymd[0];
	}
#line 418 "Simple.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Simple_month)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Simple::month(date)");
    {
	SV*	date = ST(0);
	IV	RETVAL;
	dXSTARG;
#line 338 "Simple.xs"
	{
		IV ymd[3];
		if (! SvROK (date))
			XSRETURN_UNDEF;

		days_to_ymd (SvIV (SvRV (date)), ymd);
		RETVAL = ymd[1];
	}
#line 442 "Simple.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Simple_day)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Simple::day(date)");
    {
	SV*	date = ST(0);
	IV	RETVAL;
	dXSTARG;
#line 353 "Simple.xs"
	{
		IV ymd[3];
		if (! SvROK (date))
			XSRETURN_UNDEF;

		days_to_ymd (SvIV (SvRV (date)), ymd);
		RETVAL = ymd[2];
	}
#line 466 "Simple.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Simple__stringify)
{
    dXSARGS;
    if (items < 1)
	Perl_croak(aTHX_ "Usage: Date::Simple::_stringify(date, ...)");
    {
	SV*	date = ST(0);
	SV *	RETVAL;
#line 368 "Simple.xs"
	{
		IV ymd[3];
		if (! SvROK (date))
			XSRETURN_UNDEF;

		days_to_ymd (SvIV (SvRV (date)), ymd);
		RETVAL = newSVpvf ("%04d-%02d-%02d", ymd[0] % 10000,
				   ymd[1], ymd[2]);
	}
#line 490 "Simple.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Date__Simple_as_d8)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Simple::as_d8(date)");
    {
	SV*	date = ST(0);
	SV *	RETVAL;
#line 384 "Simple.xs"
	{
		IV ymd[3];
		if (! SvROK (date))
			XSRETURN_UNDEF;

		days_to_ymd (SvIV (SvRV (date)), ymd);
		RETVAL = newSVpvf ("%04d%02d%02d", ymd[0] % 10000,
				   ymd[1], ymd[2]);
	}
#line 515 "Simple.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Date__Simple_as_ymd)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Simple::as_ymd(date)");
    SP -= items;
    {
	SV*	date = ST(0);
#line 400 "Simple.xs"
	{
		IV ymd[3];
		if (! SvROK (date))
			XSRETURN_EMPTY;

		days_to_ymd (SvIV (SvRV (date)), ymd);
		EXTEND (sp, 3);
		PUSHs (sv_2mortal (newSViv (ymd[0])));
		PUSHs (sv_2mortal (newSViv (ymd[1])));
		PUSHs (sv_2mortal (newSViv (ymd[2])));
	}
#line 542 "Simple.c"
	PUTBACK;
	return;
    }
}

XS(XS_Date__Simple__add)
{
    dXSARGS;
    if (items < 2)
	Perl_croak(aTHX_ "Usage: Date::Simple::_add(date, diff, ...)");
    {
	SV*	date = ST(0);
	IV	diff = (IV)SvIV(ST(1));
	SV *	RETVAL;
#line 417 "Simple.xs"
	{
		IV days;

		if (! is_object (date))
			XSRETURN_UNDEF;

		days = SvIV (SvRV (date)) + diff;
		RETVAL = sv_bless (newRV_noinc (newSViv (days)),
				   SvSTASH (SvRV (date)));
	}
#line 568 "Simple.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Date__Simple__subtract)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Simple::_subtract(left, right, reverse)");
    {
	SV*	left = ST(0);
	SV*	right = ST(1);
	SV*	reverse = ST(2);
	SV *	RETVAL;
#line 436 "Simple.xs"
	{
		if (! is_object (left))
			XSRETURN_UNDEF;

		if (SvTRUE (reverse))
			croak ("Can't subtract a date from a non-date");

		if (SvROK (right))
		{
			IV diff = SvIV (SvRV (left)) - SvIV (SvRV (right));
			RETVAL = newSViv (diff);
		}
		else
		{
			IV days = SvIV (SvRV (left)) - SvIV (right);
			RETVAL = sv_bless (newRV_noinc (newSViv (days)),
					   SvSTASH (SvRV (left)));
		}
	}
#line 605 "Simple.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Date__Simple__compare)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Simple::_compare(left, right, reverse)");
    {
	SV*	left = ST(0);
	SV*	right = ST(1);
	bool	reverse = (int)SvIV(ST(2));
	IV	RETVAL;
	dXSTARG;
#line 464 "Simple.xs"
	{
		IV diff;

		if (! is_object (left))
			XSRETURN_UNDEF;

		if (! is_object (right))
			right = new_for_cmp (left, right, 1);

		diff = SvIV (SvRV (left)) - SvIV (SvRV (right));
		RETVAL = diff > 0 ? 1 : (diff < 0 ? -1 : 0);

		if (reverse)
			RETVAL = -RETVAL;
	}
#line 639 "Simple.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Date__Simple__eq)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Simple::_eq(left, right, reverse)");
    {
	SV*	left = ST(0);
	SV*	right = ST(1);
	bool	reverse = (int)SvIV(ST(2));
	SV *	RETVAL;
#line 488 "Simple.xs"
	{
		if (! is_object (left))
			XSRETURN_UNDEF;

		if (! is_object (right))
			right = new_for_cmp (left, right, 0);

		if (! is_object (right))
			XSRETURN_NO;

		if (SvIV (SvRV (left)) == SvIV (SvRV (right)))
			XSRETURN_YES;
		else
			XSRETURN_NO;
	}
#line 671 "Simple.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Date__Simple__ne)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Date::Simple::_ne(left, right, reverse)");
    {
	SV*	left = ST(0);
	SV*	right = ST(1);
	bool	reverse = (int)SvIV(ST(2));
	SV *	RETVAL;
#line 512 "Simple.xs"
	{
		if (! is_object (left))
			XSRETURN_UNDEF;

		if (! is_object (right))
			right = new_for_cmp (left, right, 0);

		if (! is_object (right))
			XSRETURN_YES;

		if (SvIV (SvRV (left)) == SvIV (SvRV (right)))
			XSRETURN_NO;
		else
			XSRETURN_YES;
	}
#line 704 "Simple.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Date__Simple_day_of_week)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Date::Simple::day_of_week(date)");
    {
	SV*	date = ST(0);
	IV	RETVAL;
	dXSTARG;
#line 534 "Simple.xs"
	{
		IV days;
		if (! SvROK (date))
			XSRETURN_UNDEF;

		RETVAL = (SvIV (SvRV (date)) + 4) % 7;
		if (RETVAL < 0)
			RETVAL += 7;
	}
#line 730 "Simple.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Date__Simple)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Date::Simple::ymd", XS_Date__Simple_ymd, file);
        newXS("Date::Simple::d8", XS_Date__Simple_d8, file);
        newXS("Date::Simple::leap_year", XS_Date__Simple_leap_year, file);
        newXS("Date::Simple::days_in_month", XS_Date__Simple_days_in_month, file);
        newXS("Date::Simple::validate", XS_Date__Simple_validate, file);
        newXS("Date::Simple::ymd_to_days", XS_Date__Simple_ymd_to_days, file);
        newXS("Date::Simple::days_since_1970", XS_Date__Simple_days_since_1970, file);
        newXS("Date::Simple::days_to_ymd", XS_Date__Simple_days_to_ymd, file);
        newXS("Date::Simple::year", XS_Date__Simple_year, file);
        newXS("Date::Simple::month", XS_Date__Simple_month, file);
        newXS("Date::Simple::day", XS_Date__Simple_day, file);
        newXS("Date::Simple::_stringify", XS_Date__Simple__stringify, file);
        newXS("Date::Simple::as_d8", XS_Date__Simple_as_d8, file);
        newXS("Date::Simple::as_ymd", XS_Date__Simple_as_ymd, file);
        newXS("Date::Simple::_add", XS_Date__Simple__add, file);
        newXS("Date::Simple::_subtract", XS_Date__Simple__subtract, file);
        newXS("Date::Simple::_compare", XS_Date__Simple__compare, file);
        newXS("Date::Simple::_eq", XS_Date__Simple__eq, file);
        newXS("Date::Simple::_ne", XS_Date__Simple__ne, file);
        newXS("Date::Simple::day_of_week", XS_Date__Simple_day_of_week, file);
    XSRETURN_YES;
}

