# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1208978343);
user_pref("app.update.lastUpdateTime.background-update-timer", 1208978343);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1208978343);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1208978343);
user_pref("browser.download.lastDir", "/home/e28700/Desktop");
user_pref("browser.startup.homepage_override.mstone", "rv:1.8.1.3");
user_pref("extensions.lastAppVersion", "2.0.0.3");
user_pref("intl.charsetmenu.browser.cache", "windows-1252, ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("security.warn_submit_insecure", false);
user_pref("urlclassifier.tableversion.goog-black-enchash", "1.49337");
user_pref("urlclassifier.tableversion.goog-black-url", "1.20337");
user_pref("urlclassifier.tableversion.goog-white-domain", "1.30");
user_pref("urlclassifier.tableversion.goog-white-url", "1.371");
