#!/usr/local/bin/bash

usage()
{
echo "Usage: $0 fraud.dat.gz"
exit 1
}

HIST="histogram.pl"
CUT="ufalcut"
ANALY="analysis"
ZNL="znl"

[ $# -eq 1 ] || usage;
[ -d $ANALY ] || mkdir $ANALY

if [[ $1 == *.gz ]]; then 
  CMD="gzip -dc $1"
else
  CMD="cat $1"
fi

echo "#GENERAL CHECKS:" >$ANALY/fraud.gen
echo "####################################################################" >>$ANALY/fraud.gen
nor=`$ZNL $1 |awk '{print $1}'` 
echo "1. Number of records:  $nor" >>$ANALY/fraud.gen
rl=`$CMD |head -1 |wc -c`
echo "2. Record length:      $rl" >>$ANALY/fraud.gen
if ($CMD |is_sort -c1-19 &>/dev/null); then
st="Yes!"
else
st="No!!!"
fi
echo "3. Is sorted?          $st" >>$ANALY/fraud.gen
echo "4. Hash value histogram" >>$ANALY/fraud.gen
$CMD | $CUT -c1-19 |getHashValues -s |$HIST >>$ANALY/fraud.gen


#fraud.bin
$CMD | $CUT -c1-6 | $HIST -s> $ANALY/fraud.bin.hist

#fraud.type
$CMD | $CUT -c20 | $HIST > $ANALY/fraud.type.hist

#fraud.date-first
$CMD | $CUT -c21-26 | $HIST > $ANALY/fraud.date-first.hist

#fraud.time-first
$CMD | $CUT -c30-33 | $HIST > $ANALY/fraud.time-first.hist

#fraud.typeXdate
$CMD | $CUT -c20-26 | $HIST > $ANALY/fraud.typeXdate.hist

#fraud.blocked_date
$CMD | $CUT -c36-41 | $HIST > $ANALY/fraud.blocked_date.hist

#fraud.blocked_time
$CMD | $CUT -c44-47 | $HIST > $ANALY/fraud.blocked_time.hist

