#!/bin/csh -f

  echo "  "
foreach i (`/bin/ls *0186*gz`)
  echo "=================================================================="
  echo "  Processing file $i"
  gzcat $i | ufalcut -c1-6 | bmsort -S -M 500 | ufaluniq > bins.$i.file
end

  echo "=================================================================="
