#! /bin/sh
# standardize the filename in .filelist

for file in `cat /home/yxc/temp/900000724_.filelist`; 
 ############################ Modify this filelistname #
do
       filetest=`echo $file | sed 's:\.: :g' | awk '{print $4}'` 
       case "$filetest" in
           00195 | 00182)    prefix=`echo "auth"` 
	                     echo $prefix.20$file   ;;
	   00202)            prefix=`echo "card"`  
	                     echo $prefix.20$file   ;;
	   00179)            prefix=`echo "post"`  
	                     echo $prefix.20$file   ;;
	   00049)            prefix=`echo "fraud"`  
	                     echo $prefix.20$file   ;;
	   00108)            prefix=`echo "pay"`
	                     echo $prefix.20$file   ;;		     
            *)               echo "What is this? $file" ;;
	esac
done


      
